name: oauth2_slackapi
version: 0.1.0
author: jparound30 <japanese.around30@gmail.com>
homepage: https://github.com/jparound30/oauth2_slackapi
description: >
  A client library for authenticating with a Slack API service via OAuth2 on
  behalf of a user, and making authorized HTTP requests with the user's
  OAuth2 credentials.
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  collection: '^1.5.0'
  http: '>=0.11.0 <0.12.0'
  http_parser: '>=1.0.0 <4.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
